### ISSUE TITLE
CloudQuery Source Plugin Migration?

### ISSUE THREAD

**Issue by yevgenypats** [aws-samples/aws-auto-inventory#37] opened 2023-01-26 07:31 UTC
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

We are maintaining an [AWS plugin](https://www.cloudquery.io/docs/plugins/sources/aws/overview), which is widely used and users use it to sync their APIs to a database/datalake and create asset inventory, "operational data lake" and other use-cases.

As we have limited capacity to maintain all plugins, we are usually looking for the official vendor to help maintain it (similar to terraform provider).

I was curious if this would be an interesting collaboration, where we can help with the initial version (already implemented) and you will help maintain it?

This will give your users the ability to sync/ELT AWS APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by MarkAtwood** [comment] 2023-02-03 21:21
That's an interesting idea!  I can't promise anything right now, but we (the Amazon open source team) will look into it.

**Comment by yevgenypats** [comment] 2023-02-04 07:37
> That's an interesting idea! I can't promise anything right now, but we (the Amazon open source team) will look into it.

Thanks @MarkAtwood ! Also Feel free also to reach out to myself via  `yp` at `cloudquery.io`  or our discord [https://cloudquery.io/discord](https://cloudquery.io/discord)

Also, I think this can solve a lot of double work/maintenance for your managed AWS Config and AWS Asset Inventory product if you use CQ under the hood as the ELT step (and help us maintain the plugin ideally). Im suggesting this because even though we are an OSS company, this aligns quite well with our business as we are not looking to provide managed AWS Asset Inventory or managed AWS Config but rather we will provide in the future generic managed ELT Platform (And mostly developing our core framework which means more types in our type system, concurrency, destination agnostic, shared state and other feature all plugins can benefit from). so as of this time Im aware of couple of companies building and providing various managed solutions with CQ as their ELT solution under the hood.

Also, few very high level thoughts (might be missing context):
- A lot of our users (I can introduce a few of our mutual users, so we can have a shared call if that's interesting) implement their own DIY AWS Asset Inventory, FinOps, CSPM solutions with a data lake approach. i.e: CQ as their ELT solution, S3 as the storage, AWS Glue for Catalog, and Athena for querying. The reason they go this way as it gives access to the raw data, support more resources then AWS Config, cheaper and re-using all standard tools in the data-lake/data-engineering stack and so on.
- I believe re-implementing the current AWS Config, Asset-Inventory with the a data-lake/modern-data-stack approach can be a win-win for everyone. i.e for users: Managed version of what they already doing themselves, less maintenance for you as you don't need to maintain an  in-house ELT framework, get the power of the community and get more users to your managed version.

**Comment by MarkAtwood** [comment] 2023-02-08 18:39
I am closing this issue because it's not a bug in this code.  Thoughts on this proposal are still ongoing.  I am reachable in Amazon at atwoodm@amazon.com

**Comment by valter-silva-au** [comment] 2023-02-08 21:48
Thank you Mark.

**Comment by yevgenypats** [comment] 2023-02-08 22:04
Thanks @MarkAtwood! Just dropped a note via email.

**Closed as completed** 2023-02-09 08:59 UTC
