### ISSUE TITLE
running on Ubuntu 18.04, glibc requirement and version issue

### ISSUE THREAD

**Issue by darkwizard242** [aws-samples/aws-auto-inventory#2] opened 2021-05-04 01:45 UTC
Hi,

Upon trying to run the linux binary on Ubuntu 18.04, `aws-auto-inventory` appears to have a requirement on glibc:

```shell
$ aws-auto-inventory 
[24646] Error loading Python lib '/tmp/_MEIXX3OpN/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIXX3OpN/libpython3.9.so.1.0)
```

While I did install glibc-source, the package version available in Ubuntu repositories is 2.27:

```shell
Package: glibc-source
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 23845
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Multi-Arch: foreign
Source: glibc
Version: 2.27-3ubuntu1.4
Replaces: eglibc-source
Recommends: xz-utils
Conflicts: eglibc-source
Description: GNU C Library: sources
 This package contains the sources and patches which are needed to
 build glibc.
Homepage: https://www.gnu.org/software/libc/libc.html
Original-Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Original-Vcs-Browser: https://salsa.debian.org/glibc-team/glibc
Original-Vcs-Git: https://salsa.debian.org/glibc-team/glibc.git
```

Any chance of packaging required dependencies into the binary file itself, like aws-cli v2?

**Comment by valter-silva-au** [comment] 2021-05-07 07:12
Hi @darkwizard242, thank you for opening this issue. I'm trying to replicate this issue on a Docker image (`ubuntu:bionic`) however I'm not able to reproduce it. All dependencies are included in the binary provided. If you like, you could clone the project and build the binary locally, perhaps that solves the problem.

**Comment by darkwizard242** [comment] 2021-05-07 19:55
Hi @valter-silva-au , thank you for checking up on this issue. It's a bit strange but I seem to be observing it using `ubuntu:bionic` as well..

Commands executed:
```shell
$ docker run -it --rm ubuntu:bionic bash

$ apt-get update && apt-get install -y wget

$ wget -O /usr/local/bin/aws-auto-inventory https://github.com/aws-samples/aws-auto-inventory/releases/download/0.1.0/aws-auto-inventory-linux-x86_64

$ chmod +x /usr/local/bin/aws-auto-inventory

$ aws-auto-inventory --help
[2605] Error loading Python lib '/tmp/_MEIJTPAbj/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIJTPAbj/libpython3.9.so.1.0)
```

Would you mind trying the above locally as well and confirm if whether or not you get identical error please?

**Comment by valter-silva-au** [comment] 2021-06-05 14:24
Hi @darkwizard242 , I've tried your commands and indeed there's an issue with the missing `GLIBC`. I've found [this thread](https://stackoverflow.com/questions/59483026/error-loading-python-lib-tmp-meitueauk-libpython3-7m-so-1-0-dlopen-lib-x8) on StackOverflow. And apparently `ubuntu 18.04` comes with an older version of `GLIBC`:

```
root@a6ca76bf4136:/# ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.3) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

I've tested the same commands, however using `ubuntu:20.04`, and it worked!
```
docker run -it --rm ubuntu:focal bash
apt-get update && apt-get install -y wget
wget -O /usr/local/bin/aws-auto-inventory https://github.com/aws-samples/aws-auto-inventory/releases/download/0.1.0/aws-auto-inventory-linux-x86_64
chmod +x /usr/local/bin/aws-auto-inventory
aws-auto-inventory 
usage: aws-auto-inventory [-h] --name NAME
aws-auto-inventory: error: the following arguments are required: --name/-n
``` 

And now  testing the `GLIBC` v version on Ubuntu 20.04:
```
root@be4bb32fb262:/# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Based on this, I'm closing this issue, please feel free to open a new issue if the problem persists.

**Closed as completed by valter-silva-au** 2021-06-05 14:24 UTC
